# Generated by Django 6.0.4 on 2026-04-25 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre del Ejercicio')),
                ('grupo_muscular', models.CharField(max_length=100, verbose_name='Grupo Muscular')),
            ],
            options={
                'verbose_name': 'Ejercicio',
                'verbose_name_plural': 'Ejercicios',
            },
        ),
        migrations.CreateModel(
            name='Restriccion_Fisica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Zona de dolor o Patología')),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Restricción Física',
                'verbose_name_plural': 'Restricciones Físicas',
            },
        ),
        migrations.CreateModel(
            name='Contraindicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_bloqueo_absoluto', models.BooleanField(default=True, verbose_name='¿Bloquea el ejercicio por completo?')),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='triage.ejercicio')),
                ('restriccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='triage.restriccion_fisica')),
            ],
            options={
                'verbose_name': 'Contraindicación',
                'verbose_name_plural': 'Contraindicaciones',
            },
        ),
        migrations.AddField(
            model_name='ejercicio',
            name='restricciones_vinculadas',
            field=models.ManyToManyField(through='triage.Contraindicacion', to='triage.restriccion_fisica', verbose_name='Contraindicado para'),
        ),
        migrations.CreateModel(
            name='Usuario_Restriccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel_dolor_eva', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], verbose_name='Nivel de Dolor (EVA 1-10)')),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('restriccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='triage.restriccion_fisica')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Restricción de Usuario',
                'verbose_name_plural': 'Restricciones de Usuarios',
            },
        ),
    ]
