# Generated by Django 6.0.4 on 2026-04-25 23:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usuario',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.AddField(
            model_name='usuario',
            name='acepta_terminos',
            field=models.BooleanField(default=False, verbose_name='Acepto los términos y consentimiento informado'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='coach_asignado',
            field=models.ForeignKey(blank=True, limit_choices_to={'es_coach': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mis_clientes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usuario',
            name='descripcion_lesion',
            field=models.TextField(blank=True, null=True, verbose_name='Describe tu lesión'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='estado_cliente',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('alerta', 'En Alerta'), ('pendiente', 'Pendiente de Revisión')], default='activo', max_length=20),
        ),
        migrations.AddField(
            model_name='usuario',
            name='lesion_previa',
            field=models.BooleanField(default=False, verbose_name='¿Tienes alguna lesión diagnosticada?'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='lugar_entrenamiento',
            field=models.CharField(blank=True, choices=[('casa', 'En Casa'), ('gimnasio', 'Gimnasio'), ('aire_libre', 'Al Aire Libre')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='objetivo_principal',
            field=models.CharField(blank=True, choices=[('salud', 'Salud General'), ('fuerza', 'Ganar Fuerza'), ('movilidad', 'Mejorar Movilidad'), ('peso', 'Bajar de Peso')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='requiere_revision',
            field=models.BooleanField(default=False, verbose_name='Requiere Revisión Manual (EVA alto)'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='tiempo_disponible',
            field=models.CharField(blank=True, choices=[('15', '15 minutos'), ('30', '30 minutos'), ('45', '45+ minutos')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='usuario',
            name='ultima_actividad',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='es_cliente',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='es_coach',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefono',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Teléfono'),
        ),
    ]
