# Generated by Django 6.0.4 on 2026-04-26 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_usuario_options_usuario_acepta_terminos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='estado_coach',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=20, verbose_name='Estado del Coach'),
        ),
    ]
