# Generated by Django 6.0.4 on 2026-04-25 13:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('triage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alerta_Inactividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_inactividad', models.IntegerField(choices=[(3, '3 Días'), (7, '7 Días'), (14, '14 Días')])),
                ('fecha_disparo', models.DateTimeField(auto_now_add=True)),
                ('resuelta', models.BooleanField(default=False, verbose_name='¿Contactado por Coach?')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Alerta de Inactividad',
                'verbose_name_plural': 'Alertas de Inactividad',
            },
        ),
        migrations.CreateModel(
            name='Rutina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_asignacion', models.DateField(auto_now_add=True)),
                ('completada', models.BooleanField(default=False)),
                ('coach', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rutinas_coach', to=settings.AUTH_USER_MODEL)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rutinas_cliente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rutina',
                'verbose_name_plural': 'Rutinas',
            },
        ),
        migrations.CreateModel(
            name='Evaluacion_PostSesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('esfuerzo_rpe', models.IntegerField(choices=[(1, '1'), (2, '2'), (3, '3'), (4, '4'), (5, '5'), (6, '6'), (7, '7'), (8, '8'), (9, '9'), (10, '10')], verbose_name='Esfuerzo Percibido (RPE 1-10)')),
                ('comentario_usuario', models.TextField(blank=True, null=True)),
                ('fecha_evaluacion', models.DateTimeField(auto_now_add=True)),
                ('rutina', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='entrenamiento.rutina')),
            ],
            options={
                'verbose_name': 'Evaluación Post-Sesión',
                'verbose_name_plural': 'Evaluaciones Post-Sesión',
            },
        ),
        migrations.CreateModel(
            name='Detalle_Rutina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('series', models.IntegerField(default=3)),
                ('repeticiones', models.IntegerField(default=10)),
                ('peso_sugerido_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('ejercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='triage.ejercicio')),
                ('rutina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='entrenamiento.rutina')),
            ],
            options={
                'verbose_name': 'Detalle de Rutina',
                'verbose_name_plural': 'Detalles de Rutina',
            },
        ),
    ]
