# Generated by Django 6.0.4 on 2026-04-26 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrenamiento', '0002_alter_rutina_coach'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alerta_inactividad',
            name='resuelta',
        ),
        migrations.AddField(
            model_name='alerta_inactividad',
            name='estado_alerta',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('gestionada', 'Gestionada')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='alerta_inactividad',
            name='fecha_resolucion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='alerta_inactividad',
            name='notas_auditoria',
            field=models.TextField(blank=True, null=True, verbose_name='Notas del Coach (Auditoría)'),
        ),
    ]
